version: '3.9'
services:
  # Development Service
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev

  # Production Service
  app-prod:
    container_name: nestjs-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - '8080:3000'
    depends_on:
      - db
    profiles:
      - prod

  # Database Service (PostgreSQL)
  db:
    image: postgres:17-alpine
    container_name: nestjs-database
    environment:
      - POSTGRES_USER=fatah
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-pgadmin4 
    environment:
      - PGADMIN_DEFAULT_EMAIL=adminfatah@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - '5050:80'
    depends_on:
      - db
    profiles:
      - dev

volumes:
  db-data:
